DROP TABLE IF EXISTS "User";
CREATE TABLE "User" (
	"Id"			SERIAL PRIMARY KEY NOT NULL,
	"UserName"		VARCHAR(255) NOT NULL,
	"Password"		VARCHAR(255) NOT NULL,
	"Status"		INTEGER NOT NULL DEFAULT 1
);

DROP TABLE IF EXISTS "Books";
CREATE TABLE "Books" (
	"Id"			SERIAL PRIMARY KEY NOT NULL,
	"Title"			VARCHAR(255) NOT NULL,
	"PurchaseDate"	VARCHAR(255) NOT NULL,
	"Status"		INTEGER NOT NULL DEFAULT 1
);
