package RBACTest::Model::RBACTestDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'RBACTest::Schema',
    
    
);

=head1 NAME

RBACTest::Model::RBACTestDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<RBACTest>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<RBACTest::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Sheeju Alex

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
